# Generated by Django 5.0.6 on 2024-06-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_cliente_data_criacao_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
