# Generated by Django 5.0.6 on 2024-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_alter_cliente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('I', 'Não Informado'), ('M', 'Masculino'), ('F', 'Feminino')], default='I', max_length=1),
        ),
    ]
