# Generated by Django 5.0.6 on 2024-06-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0014_alter_cliente_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=16),
        ),
    ]
