# Generated by Django 5.0.6 on 2024-06-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0015_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
