# Generated by Django 5.0.6 on 2024-06-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0016_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comentario',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
    ]
