# Generated by Django 5.0.6 on 2024-06-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0017_alter_cliente_comentario_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comentario',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
