# Generated by Django 5.0.6 on 2024-07-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0019_alter_cliente_email_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
