# Generated by Django 5.0.6 on 2024-07-06 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0024_alter_cliente_cpf_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2,3}[0-9]{5}-?[0-9]{4}$', 'O "número" fornecido é inválido!')]),
        ),
    ]
