# Generated by Django 5.0.6 on 2024-07-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0030_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Nome do Cliente', max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(help_text='Sobrenome do Cliente', max_length=45),
        ),
    ]
