# Generated by Django 5.0.6 on 2024-07-07 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0031_alter_cliente_nome_alter_cliente_sobrenome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='celular',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', help_text='11122233399', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'O "CPF" deve conter exatamente 11 números!')]),
        ),
    ]
