# Generated by Django 5.0.6 on 2024-07-07 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0032_rename_telefone_cliente_celular_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(help_text='11 90000-0000', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2,3} ?[0-9]{5}-?[0-9]{4}$', 'O "número" fornecido é inválido!')]),
        ),
    ]
