# Generated by Django 5.0.6 on 2024-08-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0033_alter_cliente_celular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ativo',
            new_name='status',
        ),
    ]
